# Generated by Django 6.1 on 2026-09-02 08:13

import autoslug.fields
import django.db.models.deletion
import todoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=100, populate_from='name', slugify=todoapp.models.custom_slugify, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='TimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Категория')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=100, populate_from='name', slugify=todoapp.models.custom_slugify, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория по времени',
                'verbose_name_plural': 'Категории по времени',
            },
        ),
        migrations.CreateModel(
            name='AllTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, max_length=100, null=True, populate_from='name', slugify=todoapp.models.custom_slugify, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='Описание')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='todoapp.status', verbose_name='Статус выполнения')),
                ('time_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.timecategory', verbose_name='Категория времени')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
